"use client";
import {useState} from "react";
import {useQuery,useMutation,Authenticated,Unauthenticated,AuthLoading} from "convex/react";
import {SignInButton,UserButton} from "@clerk/nextjs";
import {api} from "@/convex/_generated/api";
import type {Id} from "@/convex/_generated/dataModel";
import {Plus,Clapperboard,Search,Trash2,ArrowUpRight,BookOpen} from "lucide-react";
import {toast} from "sonner";
import {Button,Card,Badge,Input,Dialog,DialogContent,DialogTitle,DialogDescription,DialogTrigger} from "@/components/ui/primitives";
import {MissionEditor} from "@/components/mission-editor";
import {blank,example} from "@/lib/mission";
export default function Home(){return <><AuthLoading><div className="grid min-h-screen place-items-center text-sm text-neutral-400">Loading workspace…</div></AuthLoading><Unauthenticated><main className="grid min-h-screen place-items-center p-6"><Card className="max-w-lg space-y-5 p-10 text-center"><Clapperboard className="mx-auto size-10 text-accent"/><Badge>OUARDOS / CASA NEGRA</Badge><h1 className="text-4xl font-bold tracking-tight">Mission Studio</h1><p className="text-neutral-400">Write cinematic missions and systemic opportunities with objectives, choices, screenplay and QA in one place.</p><SignInButton mode="modal"><Button>Sign in to your workspace</Button></SignInButton></Card></main></Unauthenticated><Authenticated><Workspace/></Authenticated></>}
function Workspace(){const missions=useQuery(api.missions.list);const create=useMutation(api.missions.create);const remove=useMutation(api.missions.remove);const [selected,setSelected]=useState<Id<"missions">|null>(null),[search,setSearch]=useState(""),[adding,setAdding]=useState(false);const current=missions?.find(m=>m._id===selected);
 async function add(useExample:boolean){setAdding(true);try{const id=await create({draft:useExample?example:{...blank,code:`CN_STORY_${String((missions?.length??0)+1).padStart(3,"0")}`}});setSelected(id);toast.success("Mission created");}catch(e){toast.error(e instanceof Error?e.message:"Unable to create mission");}finally{setAdding(false)}}
 async function del(id:Id<"missions">){if(!window.confirm("Delete this mission permanently?"))return;try{await remove({id});toast.success("Mission deleted");}catch(e){toast.error(e instanceof Error?e.message:"Delete failed");}}
 if(current)return <MissionEditor key={current._id} id={current._id} initial={current} notionUrl={current.notionUrl} onBack={()=>setSelected(null)}/>;
 return <main className="min-h-screen"><header className="border-b border-border"><div className="mx-auto flex max-w-7xl items-center justify-between p-5 md:px-8"><div className="flex items-center gap-3"><div className="rounded-lg bg-accent p-2 text-neutral-950"><Clapperboard className="size-5"/></div><div><p className="text-sm font-black tracking-widest">CASA NEGRA</p><p className="text-xs text-neutral-400">MISSION STUDIO</p></div></div><UserButton/></div></header><div className="mx-auto max-w-7xl px-5 py-10 md:px-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><Badge>OUARDOS PRODUCTION</Badge><h1 className="mt-3 text-4xl font-bold tracking-tight md:text-5xl">Your missions<span className="text-accent">.</span></h1><p className="mt-3 text-neutral-400">Design compelling situations. Give the player meaningful choices.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={adding} onClick={()=>add(true)}><BookOpen className="size-4"/> Example</Button><Button disabled={adding} onClick={()=>add(false)}><Plus className="size-4"/> New mission</Button></div></div><Card className="mb-7 flex items-center gap-3 p-4"><Search className="size-5 text-neutral-500"/><Input className="border-0 bg-transparent" placeholder="Search titles, IDs or districts…" value={search} onChange={e=>setSearch(e.target.value)}/><Badge>{missions?.length??"…"} total</Badge></Card><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{missions?.filter(m=>(m.title+" "+m.code+" "+m.district).toLowerCase().includes(search.toLowerCase())).map(m=><Card key={m._id} className="group flex min-h-60 flex-col justify-between p-6 transition-colors hover:border-accent"><div><div className="mb-6 flex items-center justify-between"><Badge>{m.status}</Badge><Button variant="ghost" size="icon" title="Delete mission" onClick={()=>del(m._id)}><Trash2 className="size-4"/></Button></div><p className="font-mono text-xs text-accent">{m.code}</p><h2 className="mt-2 text-2xl font-bold">{m.title}</h2><p className="mt-3 line-clamp-2 text-sm text-neutral-400">{m.summary||"No summary yet."}</p></div><div className="mt-7 flex items-center justify-between border-t border-border pt-4"><span className="text-xs text-neutral-400">{m.district} · {m.objectives.length} objectives</span><Button variant="ghost" size="sm" onClick={()=>setSelected(m._id)}>Edit <ArrowUpRight className="size-4"/></Button></div></Card>)}{missions?.length===0&&<Card className="col-span-full space-y-4 p-12 text-center"><Clapperboard className="mx-auto size-9 text-accent"/><h2 className="text-xl font-bold">Your first story starts here</h2><p className="text-neutral-400">Create a blank mission or load The Last Delivery as an editable example.</p><Button onClick={()=>add(true)}>Start with example</Button></Card>}</div></div></main>}
