"use client";
import {useState,useEffect,useRef} from "react";
import {useMutation} from "convex/react";
import {api} from "@/convex/_generated/api";
import type {Id} from "@/convex/_generated/dataModel";
import {ArrowLeft,BookOpen,Check,ChevronDown,Download,FileText,GitBranch,GripVertical,Plus,Save,Send,Trash2,Clapperboard,ClipboardCheck,ExternalLink} from "lucide-react";
import {toast} from "sonner";
import {Badge,Button,Card,Field,Input,Textarea,Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/primitives";
import {makeId,type MissionDraft,type Objective,type Scene,type Choice} from "@/lib/mission";
import {missionMarkdown,downloadMarkdown} from "@/lib/export";
const sections=[{id:"overview",label:"Overview",icon:FileText},{id:"flow",label:"Objectives",icon:GripVertical},{id:"scenes",label:"Screenplay",icon:Clapperboard},{id:"choices",label:"Choices",icon:GitBranch},{id:"qa",label:"QA & Notes",icon:ClipboardCheck}] as const;
export function MissionEditor({id,initial,onBack,notionUrl}:{id:Id<"missions">;initial:MissionDraft;onBack:()=>void;notionUrl?:string}){
 const [draft,setDraft]=useState<MissionDraft>(initial),[active,setActive]=useState<string>("overview"),[saving,setSaving]=useState(false),[exporting,setExporting]=useState(false);const current=useRef(draft);useEffect(()=>{current.current=draft},[draft]);
 const update=useMutation(api.missions.update);const recordNotion=useMutation(api.missions.recordNotion);
 function patch<K extends keyof MissionDraft>(key:K,value:MissionDraft[K]){setDraft(prev=>({...prev,[key]:value}));}
 async function save(){setSaving(true);try{await update({id,draft:current.current});toast.success("Mission saved");}catch(e){toast.error(e instanceof Error?e.message:"Save failed");}finally{setSaving(false)}}
 async function exportNotion(){setExporting(true);try{await update({id,draft:current.current});const response=await fetch("/api/notion/export",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({missionId:id})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Notion export failed");await recordNotion({id,pageId:result.pageId,url:result.url});toast.success("Exported to Notion");window.open(result.url,"_blank","noopener,noreferrer");}catch(e){toast.error(e instanceof Error?e.message:"Export failed");}finally{setExporting(false)}}
 function modifyObjective(index:number,key:keyof Objective,value:string|boolean){patch("objectives",draft.objectives.map((o,i)=>i===index?{...o,[key]:value}:o));}
 function modifyScene(index:number,key:keyof Scene,value:string){patch("scenes",draft.scenes.map((o,i)=>i===index?{...o,[key]:value}:o));}
 function modifyChoice(index:number,key:keyof Choice,value:string){patch("choices",draft.choices.map((o,i)=>i===index?{...o,[key]:value}:o));}
 const input=(value:string,onChange:(s:string)=>void,placeholder="")=><Input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>;
 const textarea=(value:string,onChange:(s:string)=>void,placeholder="",rows=4)=><Textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} rows={rows}/>;
 return <div className="min-h-screen pb-24"><header className="sticky top-0 z-20 border-b border-border bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-7xl flex-wrap items-center gap-3 px-4 py-3 md:px-8"><Button variant="ghost" size="sm" onClick={onBack}><ArrowLeft className="size-4"/> Missions</Button><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{draft.title}</p><p className="text-xs text-neutral-400">{draft.code} · {draft.status.toUpperCase()}</p></div><Button variant="outline" size="sm" onClick={()=>downloadMarkdown(draft)}><Download className="size-4"/><span className="hidden sm:inline">Markdown</span></Button><Button variant="outline" size="sm" disabled={exporting} onClick={exportNotion}><Send className="size-4"/>{exporting?"Exporting…":<><span className="hidden sm:inline">Export to</span> Notion</>}</Button><Button size="sm" disabled={saving} onClick={save}><Save className="size-4"/>{saving?"Saving…":"Save"}</Button></div></header>
 <div className="mx-auto max-w-7xl px-4 pt-8 md:px-8"><div className="mb-7"><Badge>MISSION DESIGN DOCUMENT</Badge><h1 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">{draft.title}</h1><p className="mt-2 text-sm text-neutral-400">Write the story. Design the actions. Define what happens when players break the plan.</p></div>
 <Tabs value={active} onValueChange={setActive}><TabsList>{sections.map(s=><TabsTrigger value={s.id} key={s.id} className="flex items-center gap-2"><s.icon className="size-4"/>{s.label}</TabsTrigger>)}</TabsList>
 <TabsContent value="overview"><div className="grid gap-5 lg:grid-cols-[2fr_1fr]"><Card className="space-y-5 p-5 md:p-7"><h2 className="text-xl font-bold">Mission identity</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Title">{input(draft.title,v=>patch("title",v),"The Last Delivery")}</Field><Field label="Mission ID">{input(draft.code,v=>patch("code",v),"CN_STORY_001")}</Field><Field label="Primary district">{input(draft.district,v=>patch("district",v),"Maarifa")}</Field><Field label="Playtime (minutes)"><Input min={1} max={240} type="number" value={draft.duration} onChange={e=>patch("duration",Math.max(1,Number(e.target.value)||1))}/></Field></div><Field label="One-line hook">{textarea(draft.summary,v=>patch("summary",v),"What makes this mission memorable?",2)}</Field><Field label="Narrative premise" helper="Character motivation, conflict and the change this mission causes.">{textarea(draft.premise,v=>patch("premise",v),"A straightforward job goes wrong…",7)}</Field></Card><div className="space-y-5"><Card className="space-y-4 p-5"><h2 className="font-bold">Production status</h2><Field label="Current stage"><select className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm" value={draft.status} onChange={e=>patch("status",e.target.value as MissionDraft["status"])}>{["idea","draft","review","ready"].map(s=><option key={s}>{s}</option>)}</select></Field><div className="grid grid-cols-2 gap-2"><div className="rounded-lg bg-muted p-3"><p className="text-2xl font-bold">{draft.objectives.length}</p><p className="text-xs text-neutral-400">Objectives</p></div><div className="rounded-lg bg-muted p-3"><p className="text-2xl font-bold">{draft.scenes.length}</p><p className="text-xs text-neutral-400">Scenes</p></div></div></Card><Card className="space-y-3 p-5"><BookOpen className="size-5 text-accent"/><h3 className="font-bold">Keep it playable</h3><p className="text-sm leading-relaxed text-neutral-400">Give each objective a meaningful player decision. Use driving as a setting for tension, dialogue, pursuits or discoveries—not as filler.</p>{notionUrl&&<a href={notionUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-sm text-accent">Open previous Notion export <ExternalLink className="size-3"/></a>}</Card></div></div></TabsContent>
 <TabsContent value="flow"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Player objectives</h2><p className="text-sm text-neutral-400">Define entry, success, failure and checkpoint behaviour for every beat.</p></div><Button onClick={()=>patch("objectives",[...draft.objectives,{id:`OBJ_${String((draft.objectives.length+1)*10).padStart(3,"0")}`,title:"New objective",kind:"systemic",description:"",entry:"",completion:"",failure:"",checkpoint:false}])}><Plus className="size-4"/> Add objective</Button></div><div className="space-y-4">{draft.objectives.map((o,i)=><Card className="p-5" key={o.id}><div className="mb-4 flex flex-wrap items-center gap-2"><Badge>{i+1} / {draft.objectives.length}</Badge><span className="text-xs font-mono text-neutral-400">{o.id}</span><div className="flex-1"/><Button variant="ghost" size="icon" title="Move up" disabled={i===0} onClick={()=>{const next=[...draft.objectives];[next[i-1],next[i]]=[next[i],next[i-1]];patch("objectives",next)}}><span aria-hidden>↑</span></Button><Button variant="ghost" size="icon" title="Move down" disabled={i===draft.objectives.length-1} onClick={()=>{const next=[...draft.objectives];[next[i],next[i+1]]=[next[i+1],next[i]];patch("objectives",next)}}><span aria-hidden>↓</span></Button><Button variant="danger" size="icon" title="Delete objective" onClick={()=>patch("objectives",draft.objectives.filter((_,j)=>j!==i))}><Trash2 className="size-4"/></Button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Objective">{input(o.title,v=>modifyObjective(i,"title",v))}</Field><Field label="Gameplay type"><select className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm" value={o.kind} onChange={e=>modifyObjective(i,"kind",e.target.value)}>{["systemic","interaction","dialogue","travel","combat","pursuit","choice"].map(k=><option key={k}>{k}</option>)}</select></Field></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Player experience">{textarea(o.description,v=>modifyObjective(i,"description",v),"What can players actually do?",3)}</Field><Field label="Entry condition">{textarea(o.entry,v=>modifyObjective(i,"entry",v),"When does this start?",3)}</Field><Field label="Completion condition">{textarea(o.completion,v=>modifyObjective(i,"completion",v),"Exact success trigger",3)}</Field><Field label="Failure & recovery">{textarea(o.failure,v=>modifyObjective(i,"failure",v),"What if the player goes off-script?",3)}</Field></div><label className="mt-4 flex cursor-pointer items-center gap-3 text-sm"><input type="checkbox" className="size-4 accent-amber-500" checked={o.checkpoint} onChange={e=>modifyObjective(i,"checkpoint",e.target.checked)}/> Create checkpoint after this objective</label></Card>)}{draft.objectives.length===0&&<Empty title="No objectives yet" description="Begin with one meaningful player action."/>}</div></TabsContent>
 <TabsContent value="scenes"><div className="mb-5 flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Screenplay</h2><p className="text-sm text-neutral-400">Cinematics, stage directions and dialogue.</p></div><Button onClick={()=>patch("scenes",[...draft.scenes,{id:makeId("SC"),slug:"NEW SCENE — LOCATION / TIME",stage:"",dialogue:""}])}><Plus className="size-4"/> Add scene</Button></div><div className="space-y-4">{draft.scenes.map((s,i)=><Card key={s.id} className="space-y-4 p-5"><div className="flex items-center justify-between"><Badge>SCENE {i+1}</Badge><Button size="icon" variant="danger" onClick={()=>patch("scenes",draft.scenes.filter((_,j)=>i!==j))} aria-label="Delete scene"><Trash2 className="size-4"/></Button></div><Field label="Scene heading">{input(s.slug,v=>modifyScene(i,"slug",v),"GARAGE — INTERIOR / NIGHT")}</Field><Field label="Stage directions">{textarea(s.stage,v=>modifyScene(i,"stage",v),"Camera, character action, sound…",4)}</Field><Field label="Dialogue">{textarea(s.dialogue,v=>modifyScene(i,"dialogue",v),"KARIM: You came.\nYASSINE: Barely.",8)}</Field></Card>)}{draft.scenes.length===0&&<Empty title="No scenes yet" description="Use scenes for moments that need precise cinematic direction."/>}</div></TabsContent>
 <TabsContent value="choices"><div className="mb-5 flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Branching decisions</h2><p className="text-sm text-neutral-400">Meaningful player decisions and lasting consequences.</p></div><Button onClick={()=>patch("choices",[...draft.choices,{id:makeId("CH"),prompt:"",optionA:"",consequenceA:"",optionB:"",consequenceB:""}])}><Plus className="size-4"/> Add choice</Button></div><div className="space-y-4">{draft.choices.map((c,i)=><Card key={c.id} className="space-y-5 p-5"><div className="flex items-center justify-between"><Badge>CHOICE {i+1}</Badge><Button variant="danger" size="icon" onClick={()=>patch("choices",draft.choices.filter((_,j)=>i!==j))} aria-label="Delete choice"><Trash2 className="size-4"/></Button></div><Field label="Decision point">{input(c.prompt,v=>modifyChoice(i,"prompt",v),"Who does the player trust?")}</Field><div className="grid gap-4 md:grid-cols-2"><div className="space-y-3 rounded-lg border border-border p-4"><Badge>PATH A</Badge><Field label="Action">{input(c.optionA,v=>modifyChoice(i,"optionA",v))}</Field><Field label="Consequence">{textarea(c.consequenceA,v=>modifyChoice(i,"consequenceA",v))}</Field></div><div className="space-y-3 rounded-lg border border-border p-4"><Badge>PATH B</Badge><Field label="Action">{input(c.optionB,v=>modifyChoice(i,"optionB",v))}</Field><Field label="Consequence">{textarea(c.consequenceB,v=>modifyChoice(i,"consequenceB",v))}</Field></div></div></Card>)}{draft.choices.length===0&&<Empty title="No choices yet" description="Add a choice when different player actions should produce different world states."/>}</div></TabsContent>
 <TabsContent value="qa"><div className="grid gap-5 lg:grid-cols-2"><Card className="space-y-4 p-6"><h2 className="text-xl font-bold">QA acceptance criteria</h2><p className="text-sm text-neutral-400">Test restarts, lost NPCs, destroyed vehicles and sequence breaks.</p>{textarea(draft.qa,v=>patch("qa",v),"Checklist for designers and QA…",14)}</Card><Card className="space-y-4 p-6"><h2 className="text-xl font-bold">Production notes</h2><p className="text-sm text-neutral-400">Technical requirements, dependencies and open questions.</p>{textarea(draft.notes,v=>patch("notes",v),"AI behaviours, assets, audio, streaming…",14)}</Card></div><Card className="mt-5 p-5"><h3 className="mb-3 font-bold">Export preview</h3><pre className="max-h-96 overflow-auto whitespace-pre-wrap rounded-lg bg-background p-4 text-xs text-neutral-300">{missionMarkdown(draft)}</pre></Card></TabsContent>
 </Tabs></div></div>;
}
function Empty({title,description}:{title:string;description:string}){return <Card className="p-12 text-center"><p className="font-semibold">{title}</p><p className="mt-2 text-sm text-neutral-400">{description}</p></Card>}
